version: '{build}'

branches:
  only:
    - master
    
os: Visual Studio 2019

environment:
  matrix:
    - CHANNEL: stable
      ARCH: x86_64
      ABI: msvc
      TARGET: x86_64-pc-windows-msvc
      APPVEYOR_SAVE_CACHE_ON_ERROR: true
      
clone_script:
- cmd: >-
    git clone --recursive https://code.qt.io/qt-creator/qt-creator.git
    
install:
 - set
 - cmd: >-
  call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"