version: '{build}'

branches:
  only:
    - master
    
os: Visual Studio 2019

environment:
  matrix:
    - CHANNEL: stable
      ARCH: x86_64
      ABI: msvc
      TARGET: x86_64-pc-windows-msvc
      APPVEYOR_SAVE_CACHE_ON_ERROR: true
      
clone_script:
- cmd: >-
    git clone --recursive https://code.qt.io/qt-creator/qt-creator.git
    
install:
    - set
  
build_script:
    - '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\build.bat'