version: '{build}'

branches:
  only:
    - master
    
os: Visual Studio 2019

platform:
- x64

environment:
    VCVAR2015: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
    VCVAR2017: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
      
clone_script:
- cmd: git clone --recursive https://code.qt.io/qt-creator/qt-creator.git
    
install:
  - set

build_script:
  - call build.bat