version: '{build}'

branches:
  only:
    - master
    
os: Visual Studio 2019

platform:
- x64

environment:
    VCVAR2015: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
    VCVAR2017: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
    LLVM_INSTALL_DIR: 'C:\Program Files\LLVM\bin'
    QTC_DISABLE_CLANG_REFACTORING: 1
    PYTHON_INSTALL_DIR: 'C:\Python38-x64'
    QT_PATH: 'C:\Qt\5.14.1\msvc2017_64'
      
clone_script:
  - git clone --recursive https://code.qt.io/qt-creator/qt-creator.git
    
install:
  - set

build_script:
  - echo %CD%
  - mkdir qt-creator-build
  - cd qt-creator-build
  - call build.bat